// DriveNow — Vehicle Manager & Vehicle Model
// This file contains two things:
//   1. The Vehicle class — a blueprint describing what data a vehicle record holds
//   2. The VehicleManager class — contains all the methods for reading and writing vehicle data to the database
// All database operations use stored procedures (spListVehicles, spAddVehicle, etc.) for security and performance.
// Module: CTEC2713N | Developer: Ushna

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;

namespace DriveNow
{
    // The Vehicle class represents a single vehicle record — one row from the database table
    public class Vehicle
    {
        public int      VehicleID      { get; set; }  // Unique ID assigned by the database
        public string   RegistrationNo { get; set; }  // Number plate, e.g. AB12 CDE
        public string   Make           { get; set; }  // Car brand, e.g. Toyota
        public string   Model          { get; set; }  // Car model, e.g. Corolla
        public decimal  DailyRate      { get; set; }  // How much it costs to hire per day (£)
        public DateTime DateAdded      { get; set; }  // When this vehicle was added to the fleet
        public bool     IsAvailable    { get; set; }  // True = in service; False = removed from fleet
        public int      Seats          { get; set; }  // Number of passenger seats
        public string   PhotoUrl       { get; set; }  // Relative path to uploaded photo (nullable); falls back to CarImages.GetUrl if null
    }

    // VehicleManager handles all Create, Read, Update, Delete (CRUD) operations for vehicles
    public class VehicleManager
    {
        // Returns a list of all vehicles currently marked as available in the database
        public List<Vehicle> ListVehicles()
        {
            var vehicles = new List<Vehicle>();
            using (SqlConnection conn = DatabaseHelper.GetConnection())
            {
                // Call the stored procedure that returns all active vehicles
                SqlCommand cmd = new SqlCommand("spListVehicles", conn);
                cmd.CommandType = CommandType.StoredProcedure;
                SqlDataReader reader = cmd.ExecuteReader();
                // Loop through each row and convert it into a Vehicle object
                while (reader.Read()) vehicles.Add(MapReader(reader));
                reader.Close();
            }
            return vehicles;
        }

        // Looks up a single vehicle by its ID — used by the Edit and Detail pages
        public Vehicle FindVehicle(int vehicleID)
        {
            Vehicle v = null;
            using (SqlConnection conn = DatabaseHelper.GetConnection())
            {
                SqlCommand cmd = new SqlCommand("spFindVehicle", conn);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@VehicleID", vehicleID); // Pass the ID to search for
                SqlDataReader reader = cmd.ExecuteReader();
                if (reader.Read()) v = MapReader(reader); // Map the result row to a Vehicle object
                reader.Close();
            }
            return v; // Returns null if no vehicle was found with that ID
        }

        // Saves a new vehicle to the database and returns the new auto-generated ID
        public int AddVehicle(Vehicle v)
        {
            int newID = 0;
            using (SqlConnection conn = DatabaseHelper.GetConnection())
            {
                SqlCommand cmd = new SqlCommand("spAddVehicle", conn);
                cmd.CommandType = CommandType.StoredProcedure;

                // Pass all the vehicle's details as parameters to the stored procedure
                cmd.Parameters.AddWithValue("@RegistrationNo", v.RegistrationNo);
                cmd.Parameters.AddWithValue("@Make",           v.Make);
                cmd.Parameters.AddWithValue("@Model",          v.Model);
                cmd.Parameters.AddWithValue("@DailyRate",      v.DailyRate);
                cmd.Parameters.AddWithValue("@DateAdded",      v.DateAdded);
                cmd.Parameters.AddWithValue("@Seats",          v.Seats > 0 ? v.Seats : 5); // Default to 5 seats if not set

                // ExecuteScalar returns the new ID generated by the database
                object result = cmd.ExecuteScalar();
                if (result != null) newID = Convert.ToInt32(result);
            }
            return newID; // The calling page uses this ID to redirect to the new vehicle's detail page
        }

        // Updates an existing vehicle's details in the database
        public void EditVehicle(Vehicle v)
        {
            using (SqlConnection conn = DatabaseHelper.GetConnection())
            {
                SqlCommand cmd = new SqlCommand("spEditVehicle", conn);
                cmd.CommandType = CommandType.StoredProcedure;

                // Include the VehicleID so the database knows which row to update
                cmd.Parameters.AddWithValue("@VehicleID",      v.VehicleID);
                cmd.Parameters.AddWithValue("@RegistrationNo", v.RegistrationNo);
                cmd.Parameters.AddWithValue("@Make",           v.Make);
                cmd.Parameters.AddWithValue("@Model",          v.Model);
                cmd.Parameters.AddWithValue("@DailyRate",      v.DailyRate);
                cmd.Parameters.AddWithValue("@DateAdded",      v.DateAdded);
                cmd.Parameters.AddWithValue("@Seats",          v.Seats > 0 ? v.Seats : 5);
                cmd.ExecuteNonQuery(); // No return value needed — just run the update
            }
        }

        // Soft-delete: marks the vehicle as unavailable (IsAvailable = false) without deleting the record
        public void DeleteVehicle(int vehicleID)
        {
            using (SqlConnection conn = DatabaseHelper.GetConnection())
            {
                SqlCommand cmd = new SqlCommand("spDeleteVehicle", conn);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@VehicleID", vehicleID);
                cmd.ExecuteNonQuery();
            }
        }

        // Returns vehicles filtered by availability and/or date — used by the Filter and List pages
        public List<Vehicle> FilterVehicles(bool? availabilityFilter, DateTime? dateAddedFrom)
        {
            var vehicles = new List<Vehicle>();
            using (SqlConnection conn = DatabaseHelper.GetConnection())
            {
                SqlCommand cmd = new SqlCommand("spFilterVehicles", conn);
                cmd.CommandType = CommandType.StoredProcedure;

                // If no filter is given, pass DBNull so the stored procedure returns all vehicles
                cmd.Parameters.AddWithValue("@AvailabilityFilter",
                    availabilityFilter.HasValue ? (object)availabilityFilter.Value : DBNull.Value);
                cmd.Parameters.AddWithValue("@DateAddedFrom",
                    dateAddedFrom.HasValue ? (object)dateAddedFrom.Value : DBNull.Value);

                SqlDataReader reader = cmd.ExecuteReader();
                while (reader.Read()) vehicles.Add(MapReader(reader));
                reader.Close();
            }
            return vehicles;
        }

        // Validates a vehicle object before saving — returns a list of error messages if anything is wrong
        public List<string> ValidateVehicle(Vehicle v)
        {
            var errors = new List<string>();

            // Check that all required fields are filled in and within allowed limits
            if (string.IsNullOrWhiteSpace(v.RegistrationNo))      errors.Add("Registration number is required.");
            else if (v.RegistrationNo.Trim().Length > 20)          errors.Add("Registration number must be 20 characters or fewer.");
            if (string.IsNullOrWhiteSpace(v.Make))                 errors.Add("Make is required.");
            else if (v.Make.Trim().Length > 50)                    errors.Add("Make must be 50 characters or fewer.");
            if (string.IsNullOrWhiteSpace(v.Model))                errors.Add("Model is required.");
            else if (v.Model.Trim().Length > 50)                   errors.Add("Model must be 50 characters or fewer.");

            // Daily rate must be a positive number within the allowed range
            if (v.DailyRate <= 0)                                  errors.Add("Daily rate must be greater than zero.");
            if (v.DailyRate > 9999.99m)                            errors.Add("Daily rate cannot exceed 9,999.99.");

            // Date added must be a past or today's date, and no earlier than year 2000
            if (v.DateAdded > DateTime.Today)                      errors.Add("Date added cannot be in the future.");
            if (v.DateAdded < new DateTime(2000, 1, 1))            errors.Add("Date added cannot be before the year 2000.");

            return errors; // Empty list means the vehicle passed all validation checks
        }

        /// <summary>
        /// Reactivates a removed vehicle. Calls spRestoreVehicle.
        /// Sets IsAvailable = 1 so the vehicle reappears on the active list.
        /// </summary>
        public void RestoreVehicle(int vehicleID)
        {
            using (SqlConnection conn = DatabaseHelper.GetConnection())
            using (SqlCommand cmd = new SqlCommand("spRestoreVehicle", conn))
            {
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@VehicleID", vehicleID);
                cmd.ExecuteNonQuery();
            }
        }

        /// <summary>
        /// Permanently removes a vehicle record from the database. Calls spHardDeleteVehicle.
        /// Raises an error if any trip still references this vehicle — archive those trips first.
        /// </summary>
        public void HardDeleteVehicle(int vehicleID)
        {
            using (SqlConnection conn = DatabaseHelper.GetConnection())
            using (SqlCommand cmd = new SqlCommand("spHardDeleteVehicle", conn))
            {
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@VehicleID", vehicleID);
                cmd.ExecuteNonQuery();
            }
        }

        // Converts a database result row into a Vehicle object — used by all read methods above
        private Vehicle MapReader(SqlDataReader reader)
        {
            // Default to 5 seats; read safely in case of older DB schema
            int seats = 5;
            try { seats = Convert.ToInt32(reader["Seats"]); } catch { }

            // Read optional PhotoUrl (only present after Script 27 has been run)
            string photoUrl = null;
            try
            {
                object rawPhoto = reader["PhotoUrl"];
                if (rawPhoto != DBNull.Value) photoUrl = rawPhoto.ToString();
            }
            catch { /* column not yet added */ }

            // Create and return a Vehicle object filled with data from the current database row
            return new Vehicle
            {
                VehicleID      = Convert.ToInt32(reader["VehicleID"]),
                RegistrationNo = reader["RegistrationNo"].ToString(),
                Make           = reader["Make"].ToString(),
                Model          = reader["Model"].ToString(),
                DailyRate      = Convert.ToDecimal(reader["DailyRate"]),
                DateAdded      = Convert.ToDateTime(reader["DateAdded"]),
                IsAvailable    = Convert.ToBoolean(reader["IsAvailable"]),
                Seats          = seats,
                PhotoUrl       = photoUrl
            };
        }
    }
}
