//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveNow {
    public partial class BrowseFleet {
        protected global::System.Web.UI.WebControls.PlaceHolder phGuest;
        protected global::System.Web.UI.WebControls.PlaceHolder phLoggedIn;
        protected global::System.Web.UI.WebControls.Repeater rptVehicles;
        protected global::System.Web.UI.WebControls.Label lblEmpty;
        protected global::System.Web.UI.WebControls.Panel pnlBookingBanner;
        protected global::System.Web.UI.WebControls.Label lblBannerDetail;
    }
}
