//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveNow
{


    public partial class EditContributor
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// lblContributorID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblContributorID;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// txtFullName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtFullName;

        /// <summary>
        /// rfvFullName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvFullName;

        /// <summary>
        /// txtEmail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>
        /// rfvEmail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEmail;

        /// <summary>
        /// revEmail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revEmail;

        /// <summary>
        /// txtPhone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtPhone;

        /// <summary>
        /// rfvPhone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPhone;

        /// <summary>
        /// ddlContributorType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlContributorType;

        /// <summary>
        /// rfvContributorType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvContributorType;

        /// <summary>
        /// txtApplicationDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtApplicationDate;

        /// <summary>
        /// rfvApplicationDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvApplicationDate;

        /// <summary>
        /// ddlIsApproved control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlIsApproved;

        /// <summary>
        /// btnSave control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnSave;

        // ── Notes ──────────────────────────────────────────────────────────────
        protected global::System.Web.UI.WebControls.TextBox txtNotes;

        // ── Phone validator ────────────────────────────────────────────────────
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revPhone;

        // ── Driver credentials panel ───────────────────────────────────────────
        protected global::System.Web.UI.WebControls.Panel   pnlDriverSection;
        protected global::System.Web.UI.WebControls.TextBox txtLicenceNumber;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revLicenceNumber;
        protected global::System.Web.UI.WebControls.TextBox txtDateOfBirth;
        protected global::System.Web.UI.WebControls.TextBox txtLicenceIssueDate;
        protected global::System.Web.UI.WebControls.TextBox txtLicenceExpiryDate;

        // ── Vehicle details panel ──────────────────────────────────────────────
        protected global::System.Web.UI.WebControls.Panel      pnlVehicleSection;
        protected global::System.Web.UI.WebControls.TextBox    txtVehicleMake;
        protected global::System.Web.UI.WebControls.TextBox    txtVehicleModel;
        protected global::System.Web.UI.WebControls.TextBox    txtVehicleYear;
        protected global::System.Web.UI.WebControls.TextBox    txtVehicleReg;
        protected global::System.Web.UI.WebControls.TextBox    txtVehicleColour;
        protected global::System.Web.UI.WebControls.TextBox    txtVehicleSeats;
        protected global::System.Web.UI.WebControls.TextBox    txtVehicleDailyRate;

        // ── Vehicle photo upload ───────────────────────────────────────────────
        protected global::System.Web.UI.WebControls.Panel      pnlCurrentVehiclePhoto;
        protected global::System.Web.UI.WebControls.Image      imgCurrentContribVehicle;
        protected global::System.Web.UI.WebControls.CheckBox   chkRemoveVehiclePhoto;
        protected global::System.Web.UI.WebControls.Panel      pnlNoVehiclePhoto;
        protected global::System.Web.UI.WebControls.FileUpload fuContribVehiclePhoto;
        protected global::System.Web.UI.WebControls.HiddenField hfCurrentVehiclePhotoUrl;
    }
}
