//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveNow
{
    public partial class Default
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.ValidationSummary LoginValidationSummary;
        protected global::System.Web.UI.WebControls.Label LoginMessageLabel;
        protected global::System.Web.UI.WebControls.Label LoginEmailLabel;
        protected global::System.Web.UI.WebControls.TextBox LoginEmailTextBox;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator LoginEmailRequiredValidator;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator LoginEmailFormatValidator;
        protected global::System.Web.UI.WebControls.Label LoginPasswordLabel;
        protected global::System.Web.UI.WebControls.TextBox LoginPasswordTextBox;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator LoginPasswordRequiredValidator;
        protected global::System.Web.UI.WebControls.Panel pnlLoginPanel;
        protected global::System.Web.UI.WebControls.Button LoginButton;

        protected global::System.Web.UI.WebControls.ValidationSummary RegisterValidationSummary;
        protected global::System.Web.UI.WebControls.Label RegisterMessageLabel;
        protected global::System.Web.UI.WebControls.Label RegisterNameLabel;
        protected global::System.Web.UI.WebControls.TextBox RegisterNameTextBox;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RegisterNameRequiredValidator;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator RegisterNameFormatValidator;
        protected global::System.Web.UI.WebControls.CustomValidator RegisterNameSpaceValidator;
        protected global::System.Web.UI.WebControls.Label RegisterEmailLabel;
        protected global::System.Web.UI.WebControls.TextBox RegisterEmailTextBox;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RegisterEmailRequiredValidator;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator RegisterEmailFormatValidator;
        protected global::System.Web.UI.WebControls.TextBox RegisterPhoneTextBox;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RegisterPhoneRequiredValidator;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator RegisterPhoneFormatValidator;
        protected global::System.Web.UI.WebControls.Label RegisterPasswordLabel;
        protected global::System.Web.UI.WebControls.TextBox RegisterPasswordTextBox;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RegisterPasswordRequiredValidator;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator RegisterPasswordStrengthValidator;
        protected global::System.Web.UI.WebControls.Label RegisterConfirmPwLabel;
        protected global::System.Web.UI.WebControls.TextBox RegisterConfirmPwTextBox;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RegisterConfirmPwRequired;
        protected global::System.Web.UI.WebControls.CompareValidator RegisterPasswordMatchValidator;
        protected global::System.Web.UI.WebControls.Button RegisterButton;
        protected global::System.Web.UI.WebControls.HiddenField PrivacyConsentHiddenField;
        protected global::System.Web.UI.WebControls.HiddenField hfCustLoggedIn;
        protected global::System.Web.UI.WebControls.HiddenField hfCustName;
        protected global::System.Web.UI.WebControls.Label PrivacyConsentMessageLabel;

        protected global::System.Web.UI.WebControls.ValidationSummary RentValidationSummary;
        protected global::System.Web.UI.WebControls.Label RentMessageLabel;
        protected global::System.Web.UI.WebControls.Label PickupLocationLabel;
        protected global::System.Web.UI.WebControls.TextBox PickupLocationTextBox;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator PickupLocationRequiredValidator;
        protected global::System.Web.UI.WebControls.Label DropLocationLabel;
        protected global::System.Web.UI.WebControls.TextBox DropLocationTextBox;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator DropLocationRequiredValidator;
        protected global::System.Web.UI.WebControls.Label PickupDateLabel;
        protected global::System.Web.UI.WebControls.TextBox PickupDateTextBox;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator PickupDateRequiredValidator;
        protected global::System.Web.UI.WebControls.Label DropDateLabel;
        protected global::System.Web.UI.WebControls.TextBox DropDateTextBox;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator DropDateRequiredValidator;
        protected global::System.Web.UI.WebControls.Label ServiceTypeLabel;
        protected global::System.Web.UI.WebControls.DropDownList ServiceTypeDropDownList;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator ServiceTypeRequiredValidator;
        protected global::System.Web.UI.WebControls.Button RentButton;
        protected global::System.Web.UI.WebControls.Panel pnlNavGuest;
        protected global::System.Web.UI.WebControls.Panel pnlNavLoggedIn;
        protected global::System.Web.UI.WebControls.Button btnNavLogout;

        protected global::System.Web.UI.WebControls.Repeater rptFeaturedFleet;
    }
}
