//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveNow
{
    public partial class DriverEdit
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm   form1;
        protected global::System.Web.UI.WebControls.Label        lblMessage;
        protected global::System.Web.UI.WebControls.Label        lblError;
        protected global::System.Web.UI.WebControls.HiddenField  hdnDriverID;
        // Personal details
        protected global::System.Web.UI.WebControls.TextBox      txtFullName;
        protected global::System.Web.UI.WebControls.TextBox      txtPhone;
        protected global::System.Web.UI.WebControls.TextBox      txtDateOfBirth;
        protected global::System.Web.UI.WebControls.TextBox      txtJoinDate;
        // Licence
        protected global::System.Web.UI.WebControls.TextBox      txtLicenceNumber;
        protected global::System.Web.UI.WebControls.TextBox      txtLicenceIssueDate;
        protected global::System.Web.UI.WebControls.TextBox      txtLicenceExpiryDate;
        // Profile
        protected global::System.Web.UI.WebControls.DropDownList ddlGender;
        protected global::System.Web.UI.WebControls.TextBox      txtSpecialty;
        protected global::System.Web.UI.WebControls.TextBox      txtBio;
        protected global::System.Web.UI.WebControls.TextBox      txtPhotoUrl;
        // Rating
        protected global::System.Web.UI.WebControls.DropDownList ddlRating;
        // Buttons
        protected global::System.Web.UI.WebControls.Button       btnSave;
        protected global::System.Web.UI.WebControls.Button       btnBack;
    }
}
