//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveNow
{
    public partial class StaffList
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm   frmStaffList;
        protected global::System.Web.UI.WebControls.Label        lblTotalStaff;
        protected global::System.Web.UI.WebControls.Label        lblActiveStaff;
        protected global::System.Web.UI.WebControls.Label        lblFormerStaff;
        protected global::System.Web.UI.WebControls.Label        lblMessage;
        protected global::System.Web.UI.WebControls.GridView     gvStaff;
    }
}
