//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveNow
{
    public partial class VehicleDetail
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.Literal litPageTitle;
        protected global::System.Web.UI.WebControls.Panel pnlNotFound;
        protected global::System.Web.UI.WebControls.Panel pnlDetail;
        protected global::System.Web.UI.WebControls.Literal litBreadcrumb;
        protected global::System.Web.UI.WebControls.Image imgVehicle;
        protected global::System.Web.UI.WebControls.Literal litVehicleName;
        protected global::System.Web.UI.WebControls.Literal litReg;
        protected global::System.Web.UI.WebControls.Literal litRate;
        protected global::System.Web.UI.WebControls.Literal litCategory;
        protected global::System.Web.UI.WebControls.Literal litSeats;
        protected global::System.Web.UI.WebControls.Literal litDoors;
        protected global::System.Web.UI.WebControls.Literal litMileage;
        protected global::System.Web.UI.WebControls.PlaceHolder phGuest;
        protected global::System.Web.UI.WebControls.PlaceHolder phLoggedIn;
        protected global::System.Web.UI.WebControls.PlaceHolder phBookBtn;
        protected global::System.Web.UI.WebControls.PlaceHolder phLoginBtn;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor bookLink;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor loginLink;
    }
}
